INSERT INTO member (id, membername, username, password, sonof, profilepic, dob, gender, relationship_status, gaon, related_to, emailid, alive, aboutme, lastlogin, joined, approved, tokenforact) VALUES
(2, 'Harikar Thakur', '', '', NULL, NULL, NULL, 0, 0, '', NULL, '', 0, '', NULL, NULL, 0, NULL),
(17, 'Harigiv Kharajpur', '', '', 16, NULL, NULL, 0, 0, '', NULL, '', 0, '', NULL, NULL, 0, NULL),
(11, 'Shri Ram (Barheta)', '', '', 2, NULL, NULL, 0, 0, '', NULL, '', 0, '', NULL, NULL, 0, NULL),
(10, 'Balbhadra (Taralahi)', '', '', 2, NULL, NULL, 0, 0, '', NULL, '', 0, '', NULL, NULL, 0, NULL),
(16, 'Devki Nandan', '', '', 15, NULL, NULL, 0, 0, '', NULL, '', 0, '', NULL, NULL, 0, NULL),
(15, 'Madhusudan (Aahil)', '', '', 2, NULL, NULL, 0, 0, '', NULL, '', 0, '', NULL, NULL, 0, NULL),
(18, 'Chiranjiv Ratupur', '', '', 16, NULL, NULL, 0, 0, '', NULL, '', 0, '', NULL, NULL, 0, NULL),
(19, 'Hishikesh', '', '', 18, NULL, NULL, 0, 0, '', NULL, '', 0, '', NULL, NULL, 0, NULL),
(20, 'Balchand', '', '', 19, NULL, NULL, 0, 0, '', NULL, '', 0, '', NULL, NULL, 0, NULL),
(21, 'Balakram', '', '', 19, NULL, NULL, 0, 0, '', NULL, '', 0, '', NULL, NULL, 0, NULL),
(65, 'Amitabh Chandan', '', '', 62, NULL, NULL, 0, 0, '', NULL, '', 0, '', NULL, NULL, 0, NULL),
(62, 'Kashinath', '', '', 61, NULL, NULL, 0, 0, '', NULL, '', 0, '', NULL, NULL, 0, NULL),
(61, 'Baldev', '', '', 58, NULL, NULL, 0, 0, '', NULL, '', 0, '', NULL, NULL, 0, NULL),
(60, 'Haridev', '', '', 58, NULL, NULL, 0, 0, '', NULL, '', 0, '', NULL, NULL, 0, NULL),
(59, 'Govind', '', '', 58, NULL, NULL, 0, 0, '', NULL, '', 0, '', NULL, NULL, 0, NULL),
(58, 'Lalji', '', '', 55, NULL, NULL, 0, 0, '', NULL, '', 0, '', NULL, NULL, 0, NULL),
(56, 'Jagannath', '', '', 54, NULL, NULL, 0, 0, '', NULL, '', 0, '', NULL, NULL, 0, NULL),
(57, 'Vishvanath', '', '', 54, NULL, NULL, 0, 0, '', NULL, '', 0, '', NULL, NULL, 0, NULL),
(55, 'Baidhnath', '', '', 54, NULL, NULL, 0, 0, '', NULL, '', 0, '', NULL, NULL, 0, NULL),
(54, 'Kaval Krishna', '', '', 20, NULL, NULL, 0, 0, '', NULL, '', 0, '', NULL, NULL, 0, NULL),
(37, 'Paharh Singh', '', '', 19, NULL, NULL, 0, 0, '', NULL, '', 0, '', NULL, NULL, 0, NULL),
(38, 'Mangal Singh', '', '', 37, NULL, NULL, 0, 0, '', NULL, '', 0, '', NULL, NULL, 0, NULL),
(39, 'Babu Lal', '', '', 38, NULL, NULL, 0, 0, '', NULL, '', 0, '', NULL, NULL, 0, NULL),
(40, 'Pashupati', '', '', 39, NULL, NULL, 0, 0, '', NULL, '', 0, '', NULL, NULL, 0, NULL),
(41, 'Panchmani', '', '', 39, NULL, NULL, 0, 0, '', NULL, '', 0, '', NULL, NULL, 0, NULL),
(42, 'Nilambar', '', '', 40, NULL, NULL, 0, 0, '', NULL, '', 0, '', NULL, NULL, 0, NULL),
(43, 'Singheshwar', '', '', 40, NULL, NULL, 0, 0, '', NULL, '', 0, '', NULL, NULL, 0, NULL),
(44, 'Vinod', '', '', 43, NULL, NULL, 0, 0, '', NULL, '', 0, '', NULL, NULL, 0, NULL),
(45, 'Subodh', '', '', 43, NULL, NULL, 0, 0, '', NULL, '', 0, '', NULL, NULL, 0, NULL),
(46, 'Subhal Kishor', '', '', 41, NULL, NULL, 0, 0, '', NULL, '', 0, '', NULL, NULL, 0, NULL),
(47, 'Avadh Kishor', '', '', 41, NULL, NULL, 0, 0, '', NULL, '', 0, '', NULL, NULL, 0, NULL),
(49, 'Rajeshwar', '', '', 47, NULL, NULL, 0, 0, '', NULL, '', 0, '', NULL, NULL, 0, NULL),
(50, 'Arun Kumar', '', '', 49, NULL, NULL, 0, 0, '', NULL, '', 0, '', NULL, NULL, 0, NULL),
(64, 'Arvind', '', '', 62, NULL, NULL, 0, 0, '', NULL, '', 0, '', NULL, NULL, 0, NULL),
(63, 'Ashok', '', '', 62, NULL, NULL, 0, 0, '', NULL, '', 0, '', NULL, NULL, 0, NULL),
(66, 'Rituraj Ranjan', '', '', 62, NULL, NULL, 0, 0, '', NULL, '', 0, '', NULL, NULL, 0, NULL),
(67, 'Darbari', '', '', 56, NULL, NULL, 0, 0, '', NULL, '', 0, '', NULL, NULL, 0, NULL),
(68, 'Banvari', '', '', 56, NULL, NULL, 0, 0, '', NULL, '', 0, '', NULL, NULL, 0, NULL),
(69, 'Balmukund', '', '', 68, NULL, NULL, 0, 0, '', NULL, '', 0, '', NULL, NULL, 0, NULL),
(70, 'Damodar', '', '', 69, NULL, NULL, 0, 0, '', NULL, '', 0, '', NULL, NULL, 0, NULL),
(71, 'Hari Mukund', '', '', 67, NULL, NULL, 0, 0, '', NULL, '', 0, '', NULL, NULL, 0, NULL),
(72, 'Madhav Mukund', '', '', 67, NULL, NULL, 0, 0, '', NULL, '', 0, '', NULL, NULL, 0, NULL),
(73, 'Krishna Kumar', '', '', 71, NULL, NULL, 0, 0, '', NULL, '', 0, '', NULL, NULL, 0, NULL),
(74, 'Braj Kumar', '', '', 71, NULL, NULL, 0, 0, '', NULL, '', 0, '', NULL, NULL, 0, NULL),
(75, 'Jivach', '', '', 71, NULL, NULL, 0, 0, '', NULL, '', 0, '', NULL, NULL, 0, NULL),
(76, 'Gunanand', '', '', 74, NULL, NULL, 0, 0, '', NULL, '', 0, '', NULL, NULL, 0, NULL),
(77, 'Punyanand', '', '', 74, NULL, NULL, 0, 0, '', NULL, '', 0, '', NULL, NULL, 0, NULL),
(78, 'Jagatanand', '', '', 74, NULL, NULL, 0, 0, '', NULL, '', 0, '', NULL, NULL, 0, NULL),
(79, 'Neeraj', '', '', 76, NULL, NULL, 0, 0, '', NULL, '', 0, '', NULL, NULL, 0, NULL),
(80, 'Dheeraj', '', '', 76, NULL, NULL, 0, 0, '', NULL, '', 0, '', NULL, NULL, 0, NULL),
(81, 'Ganshyam', '', '', 75, NULL, NULL, 0, 0, '', NULL, '', 0, '', NULL, NULL, 0, NULL),
(82, 'Shyam Kishor', '', '', 75, NULL, NULL, 0, 0, '', NULL, '', 0, '', NULL, NULL, 0, NULL),
(83, 'Indra Kumar', '', '', 72, NULL, NULL, 0, 0, '', NULL, '', 0, '', NULL, NULL, 0, NULL),
(84, 'Kali Kumar', '', '', 72, NULL, NULL, 0, 0, '', NULL, '', 0, '', NULL, NULL, 0, NULL),
(85, 'Sunil Kumar', '', '', 83, NULL, NULL, 0, 0, '', NULL, '', 0, '', NULL, NULL, 0, NULL),
(86, 'Subodh Kumar', '', '', 83, NULL, NULL, 0, 0, '', NULL, '', 0, '', NULL, NULL, 0, NULL),
(87, 'Shiv Shankar', '', '', 83, NULL, NULL, 0, 0, '', NULL, '', 0, '', NULL, NULL, 0, NULL),
(88, 'Sujeet Kumar', '', '', 83, NULL, NULL, 0, 0, '', NULL, '', 0, '', NULL, NULL, 0, NULL),
(89, 'Sudhir Kumar', '', '', 84, NULL, NULL, 0, 0, '', NULL, '', 0, '', NULL, NULL, 0, NULL),
(90, 'Shri Lal', '', '', 57, NULL, NULL, 0, 0, '', NULL, '', 0, '', NULL, NULL, 0, NULL),
(91, 'Sundar Lal', '', '', 57, NULL, NULL, 0, 0, '', NULL, '', 0, '', NULL, NULL, 0, NULL),
(92, 'Parmanand', '', '', 90, NULL, NULL, 0, 0, '', NULL, '', 0, '', NULL, NULL, 0, NULL),
(93, 'Achyutanand', '', '', 90, NULL, NULL, 0, 0, '', NULL, '', 0, '', NULL, NULL, 0, NULL),
(101, 'Brijendra', '', '', 100, NULL, NULL, 0, 0, '', NULL, '', 0, '', NULL, NULL, 0, NULL),
(95, 'Dhirendra Lal Das', '', '', 93, NULL, NULL, 0, 0, '', NULL, '', 0, '', NULL, NULL, 0, NULL),
(96, 'Upendra Kumar Das', '', '', 93, NULL, NULL, 0, 0, '', NULL, '', 0, '', NULL, NULL, 0, NULL),
(97, 'Jitendra Kumar Das', '', '', 93, NULL, NULL, 0, 0, '', NULL, '', 0, '', NULL, NULL, 0, NULL),
(100, 'Sachidanand', '', '', 90, NULL, NULL, 0, 0, '', NULL, '', 0, '', NULL, NULL, 0, NULL),
(102, 'Ramnarayan', '', '', 101, NULL, NULL, 0, 0, '', NULL, '', 0, '', NULL, NULL, 0, NULL),
(103, 'Krishnanarayan', '', '', 101, NULL, NULL, 0, 0, '', NULL, '', 0, '', NULL, NULL, 0, NULL),
(104, 'Bachanraj Raman', '', '', 101, NULL, NULL, 0, 0, '', NULL, '', 0, '', NULL, NULL, 0, NULL),
(105, 'Yadav Singh', '', '', 19, NULL, NULL, 0, 0, '', NULL, '', 0, '', NULL, NULL, 0, NULL),
(106, 'Dev Narayan', '', '', 105, NULL, NULL, 0, 0, '', NULL, '', 0, '', NULL, NULL, 0, NULL),
(107, 'Sanphul', '', '', 105, NULL, NULL, 0, 0, '', NULL, '', 0, '', NULL, NULL, 0, NULL),
(108, 'Baccha', '', '', 105, NULL, NULL, 0, 0, '', NULL, '', 0, '', NULL, NULL, 0, NULL),
(109, 'Sabur', '', '', 105, NULL, NULL, 0, 0, '', NULL, '', 0, '', NULL, NULL, 0, NULL),
(110, 'Radhe Krishna', '', '', 108, NULL, NULL, 0, 0, '', NULL, '', 0, '', NULL, NULL, 0, NULL),
(111, 'Nikah', '', '', 108, NULL, NULL, 0, 0, '', NULL, '', 0, '', NULL, NULL, 0, NULL),
(112, 'Gauri Das', '', '', 111, NULL, NULL, 0, 0, '', NULL, '', 0, '', NULL, NULL, 0, NULL),
(186, 'Prabhash', '', '', 185, NULL, NULL, 0, 0, '', NULL, '', 0, '', NULL, NULL, 0, NULL),
(185, 'Rajeshwar', '', '', 184, NULL, NULL, 0, 0, '', NULL, '', 0, '', NULL, NULL, 0, NULL),
(184, 'Baldev', '', '', 117, NULL, NULL, 0, 0, '', NULL, '', 0, '', NULL, NULL, 0, NULL),
(117, 'HiraLal', '', '', 112, NULL, NULL, 0, 0, '', NULL, '', 0, '', NULL, NULL, 0, NULL),
(118, 'Motilal', '', '', 112, NULL, NULL, 0, 0, '', NULL, '', 0, '', NULL, NULL, 0, NULL),
(119, 'Manohar Lal', '', '', 112, NULL, NULL, 0, 0, '', NULL, '', 0, '', NULL, NULL, 0, NULL),
(120, 'Shyam Lal', '', '', 109, NULL, NULL, 0, 0, '', NULL, '', 0, '', NULL, NULL, 0, NULL),
(121, 'Nanu', '', '', 109, NULL, NULL, 0, 0, '', NULL, '', 0, '', NULL, NULL, 0, NULL),
(122, 'Hemkar', '', '', 109, NULL, NULL, 0, 0, '', NULL, '', 0, '', NULL, NULL, 0, NULL),
(123, 'Fekan', '', '', 121, NULL, NULL, 0, 0, '', NULL, '', 0, '', NULL, NULL, 0, NULL),
(124, 'Bihari', '', '', 121, NULL, NULL, 0, 0, '', NULL, '', 0, '', NULL, NULL, 0, NULL),
(125, 'Bhishan', '', '', 121, NULL, NULL, 0, 0, '', NULL, '', 0, '', NULL, NULL, 0, NULL),
(126, 'Mahadev', '', '', 124, NULL, NULL, 0, 0, '', NULL, '', 0, '', NULL, NULL, 0, NULL),
(127, 'Jagdish', '', '', 126, NULL, NULL, 0, 0, '', NULL, '', 0, '', NULL, NULL, 0, NULL),
(128, 'Vishva Mohan', '', '', 127, NULL, NULL, 0, 0, '', NULL, '', 0, '', NULL, NULL, 0, NULL),
(129, 'Lalit Mohan', '', '', 127, NULL, NULL, 0, 0, '', NULL, '', 0, '', NULL, NULL, 0, NULL),
(130, 'Munna', '', '', 125, NULL, NULL, 0, 0, '', NULL, '', 0, '', NULL, NULL, 0, NULL),
(131, 'Boua', '', '', 125, NULL, NULL, 0, 0, '', NULL, '', 0, '', NULL, NULL, 0, NULL),
(132, 'Pitambar', '', '', 125, NULL, NULL, 0, 0, '', NULL, '', 0, '', NULL, NULL, 0, NULL),
(133, 'Ajab Lal', '', '', 132, NULL, NULL, 0, 0, '', NULL, '', 0, '', NULL, NULL, 0, NULL),
(134, 'Neva Lal', '', '', 132, NULL, NULL, 0, 0, '', NULL, '', 0, '', NULL, NULL, 0, NULL),
(135, 'Shayam Lal', '', '', 132, NULL, NULL, 0, 0, '', NULL, '', 0, '', NULL, NULL, 0, NULL),
(136, 'Indramani', '', '', 122, NULL, NULL, 0, 0, '', NULL, '', 0, '', NULL, NULL, 0, NULL),
(137, 'Bhola', '', '', 136, NULL, NULL, 0, 0, '', NULL, '', 0, '', NULL, NULL, 0, NULL),
(138, 'Bhuvneshwar', '', '', 137, NULL, NULL, 0, 0, '', NULL, '', 0, '', NULL, NULL, 0, NULL),
(139, 'Jata Shankar', '', '', 138, NULL, NULL, 0, 0, '', NULL, '', 0, '', NULL, NULL, 0, NULL),
(140, 'Shiv Shankar', '', '', 138, NULL, NULL, 0, 0, '', NULL, '', 0, '', NULL, NULL, 0, NULL),
(141, 'Chandra Mohan', '', '', 138, NULL, NULL, 0, 0, '', NULL, '', 0, '', NULL, NULL, 0, NULL),
(142, 'Vinod', '', '', 138, NULL, NULL, 0, 0, '', NULL, '', 0, '', NULL, NULL, 0, NULL),
(143, 'Baleshwar', '', '', 47, NULL, NULL, 0, 0, '', NULL, '', 0, '', NULL, NULL, 0, NULL),
(144, 'Parmeshwar', '', '', 47, NULL, NULL, 0, 0, '', NULL, '', 0, '', NULL, NULL, 0, NULL),
(145, 'Sureshwar', '', '', 47, NULL, NULL, 0, 0, '', NULL, '', 0, '', NULL, NULL, 0, NULL),
(146, 'Bhairav Lal', '', '', 143, NULL, NULL, 0, 0, '', NULL, '', 0, '', NULL, NULL, 0, NULL),
(147, 'Amar Kumar Lal', '', '', 143, NULL, NULL, 0, 0, '', NULL, '', 0, '', NULL, NULL, 0, NULL),
(148, 'Murlidhar', '', '', 146, NULL, NULL, 0, 0, '', NULL, '', 0, '', NULL, NULL, 0, NULL),
(149, 'Pankaj', '', '', 145, NULL, NULL, 0, 0, '', NULL, '', 0, '', NULL, NULL, 0, NULL),
(150, 'Chandan', '', '', 145, NULL, NULL, 0, 0, '', NULL, '', 0, '', NULL, NULL, 0, NULL),
(151, 'Sukhdev', '', '', 41, NULL, NULL, 0, 0, '', NULL, '', 0, '', NULL, NULL, 0, NULL),
(152, 'Kapleshwar', '', '', 151, NULL, NULL, 0, 0, '', NULL, '', 0, '', NULL, NULL, 0, NULL),
(153, 'Jageshwar', '', '', 151, NULL, NULL, 0, 0, '', NULL, '', 0, '', NULL, NULL, 0, NULL),
(154, 'Satish Kumar Das', '', '', 152, NULL, NULL, 0, 0, '', NULL, '', 0, '', NULL, NULL, 0, NULL),
(155, 'Ashok Kumar', '', '', 152, NULL, NULL, 0, 0, '', NULL, '', 0, '', NULL, NULL, 0, NULL),
(156, 'Madhav', '', '', 155, NULL, NULL, 0, 0, '', NULL, '', 0, '', NULL, NULL, 0, NULL),
(157, 'Govind', '', '', 155, NULL, NULL, 0, 0, '', NULL, '', 0, '', NULL, NULL, 0, NULL),
(158, 'Vimal Kumar', '', '', 153, NULL, NULL, 0, 0, '', NULL, '', 0, '', NULL, NULL, 0, NULL),
(159, 'Bajrang Lal', '', '', 153, NULL, NULL, 0, 0, '', NULL, '', 0, '', NULL, NULL, 0, NULL),
(160, 'Thakur Singh', '', '', 20, NULL, NULL, 0, 0, '', NULL, '', 0, '', NULL, NULL, 0, NULL),
(161, 'Rang Lal', '', '', 160, NULL, NULL, 0, 0, '', NULL, '', 0, '', NULL, NULL, 0, NULL),
(162, 'Amrit Lal', '', '', 160, NULL, NULL, 0, 0, '', NULL, '', 0, '', NULL, NULL, 0, NULL),
(163, 'Shankar Das', '', '', 162, NULL, NULL, 0, 0, '', NULL, '', 0, '', NULL, NULL, 0, NULL),
(164, 'Bhagvat', '', '', 163, NULL, NULL, 0, 0, '', NULL, '', 0, '', NULL, NULL, 0, NULL),
(165, 'Shiv Narayan', '', '', 164, NULL, NULL, 0, 0, '', NULL, '', 0, '', NULL, NULL, 0, NULL),
(166, 'Laxmi Narayan', '', '', 164, NULL, NULL, 0, 0, '', NULL, '', 0, '', NULL, NULL, 0, NULL),
(167, 'Dayanand', '', '', 165, NULL, NULL, 0, 0, '', NULL, '', 0, '', NULL, NULL, 0, NULL),
(168, 'Khelanand', '', '', 165, NULL, NULL, 0, 0, '', NULL, '', 0, '', NULL, NULL, 0, NULL),
(169, 'Manoj', '', '', 167, NULL, NULL, 0, 0, '', NULL, '', 0, '', NULL, NULL, 0, NULL),
(170, 'Mukesh', '', '', 167, NULL, NULL, 0, 0, '', NULL, '', 0, '', NULL, NULL, 0, NULL),
(171, 'Kamlesh', '', '', 167, NULL, NULL, 0, 0, '', NULL, '', 0, '', NULL, NULL, 0, NULL),
(172, 'Chatur Bhuj', '', '', 20, NULL, NULL, 0, 0, '', NULL, '', 0, '', NULL, NULL, 0, NULL),
(173, 'Jay Ram', '', '', 172, NULL, NULL, 0, 0, '', NULL, '', 0, '', NULL, NULL, 0, NULL),
(174, 'Sita Ram', '', '', 172, NULL, NULL, 0, 0, '', NULL, '', 0, '', NULL, NULL, 0, NULL),
(175, 'Manohar', '', '', 174, NULL, NULL, 0, 0, '', NULL, '', 0, '', NULL, NULL, 0, NULL),
(176, 'Murlidhar', '', '', 175, NULL, NULL, 0, 0, '', NULL, '', 0, '', NULL, NULL, 0, NULL),
(177, 'Praveen Prakash', '', '', 96, NULL, NULL, 0, 0, '', NULL, '', 0, '', NULL, NULL, 0, NULL),
(178, 'Piyush Prakash', '', '', 96, NULL, NULL, 0, 0, '', NULL, '', 0, '', NULL, NULL, 0, NULL),
(180, 'Prabhat Prakash', '', '', 95, NULL, NULL, 0, 0, '', NULL, '', 0, '', NULL, NULL, 0, NULL),
(181, 'Mrityunjay', '', '', 89, NULL, NULL, 0, 0, '', NULL, '', 0, '', NULL, NULL, 0, NULL),
(187, 'Subhash', '', '', 185, NULL, NULL, 0, 0, '', NULL, '', 0, '', NULL, NULL, 0, NULL),
(188, 'BankeLal', '', '', 118, NULL, NULL, 0, 0, '', NULL, '', 0, '', NULL, NULL, 0, NULL),
(189, 'Rasdhari', '', '', 118, NULL, NULL, 0, 0, '', NULL, '', 0, '', NULL, NULL, 0, NULL),
(190, 'Kumar Rameshwar', '', '', 188, NULL, NULL, 0, 0, '', NULL, '', 0, '', NULL, NULL, 0, NULL),
(191, 'Kumar Dineshwar', '', '', 188, NULL, NULL, 0, 0, '', NULL, '', 0, '', NULL, NULL, 0, NULL),
(192, 'Kumar Umeshwar', '', '', 188, NULL, NULL, 0, 0, '', NULL, '', 0, '', NULL, NULL, 0, NULL),
(193, 'Kumar Rajendra (Lalit)', '', '', 190, NULL, NULL, 0, 0, '', NULL, '', 0, '', NULL, NULL, 0, NULL),
(194, 'Jitendra', '', '', 190, NULL, NULL, 0, 0, '', NULL, '', 0, '', NULL, NULL, 0, NULL),
(195, 'Narendra (Shambu)', '', '', 190, NULL, NULL, 0, 0, '', NULL, '', 0, '', NULL, NULL, 0, NULL),
(196, 'Rupak', '', '', 190, NULL, NULL, 0, 0, '', NULL, '', 0, '', NULL, NULL, 0, NULL),
(197, 'Shailesh', '', '', 190, NULL, NULL, 0, 0, '', NULL, '', 0, '', NULL, NULL, 0, NULL),
(198, 'Deepak', '', '', 191, NULL, NULL, 0, 0, '', NULL, '', 0, '', NULL, NULL, 0, NULL),
(199, 'Bhagwan', '', '', 191, NULL, NULL, 0, 0, '', NULL, '', 0, '', NULL, NULL, 0, NULL),
(200, 'Naveen', '', '', 191, NULL, NULL, 0, 0, '', NULL, '', 0, '', NULL, NULL, 0, NULL),
(201, 'Golu', '', '', 191, NULL, NULL, 0, 0, '', NULL, '', 0, '', NULL, NULL, 0, NULL),
(202, 'Piyush', '', '', 192, NULL, NULL, 0, 0, '', NULL, '', 0, '', NULL, NULL, 0, NULL),
(203, 'Babbu', '', '', 192, NULL, NULL, 0, 0, '', NULL, '', 0, '', NULL, NULL, 0, NULL),
(204, 'Nishu', '', '', 192, NULL, NULL, 0, 0, '', NULL, '', 0, '', NULL, NULL, 0, NULL),
(205, 'Satdev', '', '', 118, NULL, NULL, 0, 0, '', NULL, '', 0, '', NULL, NULL, 0, NULL),
(206, 'Kailash Bihari', '', '', 205, NULL, NULL, 0, 0, '', NULL, '', 0, '', NULL, NULL, 0, NULL),
(207, 'Bijiyanand', '', '', 205, NULL, NULL, 0, 0, '', NULL, '', 0, '', NULL, NULL, 0, NULL),
(208, 'Vinod Bihari', '', '', 205, NULL, NULL, 0, 0, '', NULL, '', 0, '', NULL, NULL, 0, NULL),
(209, 'Saket Saurav (Murari)', '', '', 206, NULL, NULL, 0, 0, '', NULL, '', 0, '', NULL, NULL, 0, NULL),
(210, 'Shishir Saurav (Rajan)', '', '', 207, NULL, NULL, 0, 0, '', NULL, '', 0, '', NULL, NULL, 0, NULL),
(211, 'Jivach Lal', '', '', 119, NULL, NULL, 0, 0, '', NULL, '', 0, '', NULL, NULL, 0, NULL),
(212, 'Devnarayan', '', '', 211, NULL, NULL, 0, 0, '', NULL, '', 0, '', NULL, NULL, 0, NULL),
(213, 'Harnarayan', '', '', 211, NULL, NULL, 0, 0, '', NULL, '', 0, '', NULL, NULL, 0, NULL),
(214, 'Sarvnarayan', '', '', 212, NULL, NULL, 0, 0, '', NULL, '', 0, '', NULL, NULL, 0, NULL),
(215, 'Dharnarayan', '', '', 212, NULL, NULL, 0, 0, '', NULL, '', 0, '', NULL, NULL, 0, NULL),
(216, 'Kharagnarayan', '', '', 212, NULL, NULL, 0, 0, '', NULL, '', 0, '', NULL, NULL, 0, NULL),
(217, 'Shivnarayan', '', '', 212, NULL, NULL, 0, 0, '', NULL, '', 0, '', NULL, NULL, 0, NULL),
(218, 'Yognarayan (Laxman)', '', '', 213, NULL, NULL, 0, 0, '', NULL, '', 0, '', NULL, NULL, 0, NULL),
(219, 'Bharat Narayan (Bhawnath)', '', '', 213, NULL, NULL, 0, 0, '', NULL, '', 0, '', NULL, NULL, 0, NULL),
(220, 'Kanahiya', '', '', 213, NULL, NULL, 0, 0, '', NULL, '', 0, '', NULL, NULL, 0, NULL),
(221, 'Sambhav', '', '', 87, NULL, NULL, 0, 0, '', NULL, '', 0, '', NULL, NULL, 0, NULL),
(222, 'Shardul Samrat Vikram (Harshit)', '', '', 86, NULL, NULL, 0, 0, '', NULL, '', 0, '', NULL, NULL, 0, NULL),
(223, 'Sushant', '', '', 85, NULL, NULL, 0, 0, '', NULL, '', 0, '', NULL, NULL, 0, NULL),
(224, 'Chunnu', '', '', 75, NULL, NULL, 0, 0, '', NULL, '', 0, '', NULL, NULL, 0, NULL),
(233, 'Siddharth Saurav (Mantun)', '', '', 208, NULL, NULL, 0, 0, '', NULL, '', 0, '', NULL, NULL, 0, NULL),
(235, 'Krishna Bihari', '', '', 189, NULL, NULL, 0, 0, '', NULL, '', 0, '', NULL, NULL, 0, NULL),
(236, 'Ram Bihari', '', '', 189, NULL, NULL, 0, 0, '', NULL, '', 0, '', NULL, NULL, 0, NULL),
(237, 'Maheshwar', '', '', 189, NULL, NULL, 0, 0, '', NULL, '', 0, '', NULL, NULL, 0, NULL),
(238, 'Dev Kumar', '', '', 235, NULL, NULL, 0, 0, '', NULL, '', 0, '', NULL, NULL, 0, NULL),
(239, 'Sitaram', '', '', 235, NULL, NULL, 0, 0, '', NULL, '', 0, '', NULL, NULL, 0, NULL),
(240, 'Chandra Mohan', '', '', 235, NULL, NULL, 0, 0, '', NULL, '', 0, '', NULL, NULL, 0, NULL),
(241, 'Chote', '', '', 235, NULL, NULL, 0, 0, '', NULL, '', 0, '', NULL, NULL, 0, NULL),
(242, 'Pappu', '', '', 235, NULL, NULL, 0, 0, '', NULL, '', 0, '', NULL, NULL, 0, NULL),
(243, 'Munna', '', '', 236, NULL, NULL, 0, 0, '', NULL, '', 0, '', NULL, NULL, 0, NULL),
(244, 'Bachun', '', '', 237, NULL, NULL, 0, 0, '', NULL, '', 0, '', NULL, NULL, 0, NULL),
(245, 'Sanjay', '', '', 237, NULL, NULL, 0, 0, '', NULL, '', 0, '', NULL, NULL, 0, NULL),
(249, 'Pramod', '', '', 140, NULL, NULL, 0, 0, '', NULL, '', 0, '', NULL, NULL, 0, NULL),
(247, 'Manoj', '', '', 140, NULL, NULL, 0, 0, '', NULL, '', 0, '', NULL, NULL, 0, NULL),
(250, 'Awdhesh Kumar', '', '', 139, NULL, NULL, 0, 0, '', NULL, '', 0, '', NULL, NULL, 0, NULL),
(251, 'Mithilesh Kumar', '', '', 139, NULL, NULL, 0, 0, '', NULL, '', 0, '', NULL, NULL, 0, NULL),
(252, ' Mr. Rajesh Kumar', '', '', 139, NULL, NULL, 0, 0, '', NULL, '', 0, '', NULL, NULL, 0, NULL),
(253, 'Mr. Dipesh Kumar', '', '', 139, NULL, NULL, 0, 0, '', NULL, '', 0, '', NULL, NULL, 0, NULL),
(254, ' Mr. Bhupesh Kumar', '', '', 139, NULL, NULL, 0, 0, '', NULL, '', 0, '', NULL, NULL, 0, NULL);
(255, 'Harsh', '', '' , 77, NULL, NULL, 0, 0, '', NULL, '', 0, '', NULL, NULL, 0, NULL);
(256, 'Harsh', '', '', 78, NULL, NULL, 0, 0, '', NULL, '', 0, '', NULL, NULL, 0, NULL);
(257, 'Bullu ji', '', '', 84, NULL, NULL, 0, 0, '', NULL, '', 0, '', NULL, NULL, 0, NULL);
(258, 'Tej Das', '', '', 64, NULL, NULL, 0, 0, '', NULL, '', 0, '', NULL, NULL, 0, NULL);
(259, 'Girdhar', '', '', 147, NULL, NULL, 0, 0, '', NULL, '', 0, '', NULL, NULL, 0, NULL);
(260, 'Kaushal Kishor', '', '', 144, NULL, NULL, 0, 0, '', NULL, '', 0, '', NULL, NULL, 0, NULL);
(261, 'Sonu', '', '', 144, NULL, NULL, 0, 0, '', NULL, '', 0, '', NULL, NULL, 0, NULL);
(262, 'Lala', '', '', 239, NULL, NULL, 0, 0, '', NULL, '', 0, '', NULL, NULL, 0, NULL);
(263, 'Deepak', '', '' , 238, NULL, NULL, 0, 0, '', NULL, '', 0, '', NULL, NULL, 0, NULL);
(264, 'Mithelesh', '', '', 238, NULL, NULL, 0, 0, '', NULL, '', 0, '', NULL, NULL, 0, NULL);
(265, 'Tinku', '', '', 238, NULL, NULL, 0, 0, '', NULL, '', 0, '', NULL, NULL, 0, NULL);
(266, 'Tinku', '', '', 215, NULL, NULL, 0, 0, '', NULL, '', 0, '', NULL, NULL, 0, NULL);
(267, 'Pintu', '', '', 215, NULL, NULL, 0, 0, '', NULL, '', 0, '', NULL, NULL, 0, NULL);
(268, 'Chintu', '', '', 218, NULL, NULL, 0, 0, '', NULL, '', 0, '', NULL, NULL, 0, NULL);
(269, 'Munna', '', '', 128, NULL, NULL, 0, 0, '', NULL, '', 0, '', NULL, NULL, 0, NULL);
(270, 'Manish', '','', 128, NULL, NULL, 0, 0, '', NULL, '', 0, '', NULL, NULL, 0, NULL);
(271, 'Sandeep', '', '', 141, NULL, NULL, 0, 0, '', NULL, '', 0, '', NULL, NULL, 0, NULL);
(272, 'Sanjay', '', '', 141, NULL, NULL, 0, 0, '', NULL, '', 0, '', NULL, NULL, 0, NULL);